[mainConfig]
appName = "mychat"
host = "0.0.0.0"
port = 8000

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "sw123456"
databaseName = "mychat"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[logConfig]
logPath = "./logs"
level = "info"
format = "json"
maxSize = 100
maxBackups = 3
maxAge = 7
compress = true
console = true